### ISSUE TITLE
Feature request: put version info in the "Info" pop-up

### ISSUE THREAD

**Issue by rayjlinden** [fescobar/allure-docker-service-ui#15]
It would be useful to put version info in the "info" pop-up.  Actually, config info and version info from Allure itself would also be nice to show here...

**Comment by fescobar** [comment]
@rayjlinden everything is in config
![image](https://user-images.githubusercontent.com/1236418/104301488-9fb72a00-54bf-11eb-9687-e78f1d1ab593.png)

**Comment by fescobar** [comment]
@rayjlinden  the same I will take in mind your suggestion for the next release. Thanks

**Comment by fescobar** [comment]
@rayjlinden your improvements was released from version 7.0.3:

https://github.com/fescobar/allure-docker-service-ui/releases/tag/v7.0.3
