### ISSUE TITLE
Improve UIX-View

### ISSUE THREAD

**Issue by fabian-castillo-developer** [fescobar/allure-docker-service-ui#20]
First and most important, thanks very much for you work, we use it every day, twice per day to check the last built results. We found your solution extremely useful. Keep it up!!

Having said this, I'm contacting you today to share UIX experience just in case that is useful. 

In our case, once the projects were configured, we frequently access the UI to check the last build results,  therefore we think that UIX should be focused mainly on viewing as much results as possible. To accomplish this, we suggest to  hide/reduce the space management option currently take. 

To show graphically what we mean,  I updated the styles online to remove some of the padding and extra margins and share an idea of a compressed layout.

![image](https://user-images.githubusercontent.com/1194406/123514033-da281400-d666-11eb-928a-bc9b968a6605.png)

Would this make sense? 
Thanks again for your fantastic work, we love the solution.
Kind regards

Fabian Castillo

**Comment by fescobar** [comment]
Hi @fabian-castillo-developer. Thank you for your feedback.
I'm a little busy these days, but any pull requests against my `beta` branch are welcome.
