### ISSUE TITLE
cookies SameSite header

### ISSUE THREAD

**Issue by brizjin** [fescobar/allure-docker-service-ui#21]
Hi! I published allure UI and service to heroku as separate docker containers app. Both has different URL. I specified ALLURE_DOCKER_PUBLIC_API_URL to service app. But can not login. Chrome says, that do not saves any cookies, and suggest, that Set-cookie header should have SameSite=None to allowed me have ui and service on different urls. How can i set that cookie by my self or why nobody else have this essue?
![image](https://user-images.githubusercontent.com/3459211/124515793-fa836b80-dde8-11eb-8322-6417f208d81f.png)

**Comment by fescobar** [comment]
Hi @brizjin 
By security that by default requires to use the same domain for api/ui. I've tried to do that configuration optional, but there is an issue with Flask. That config comes from the API, not from the UI. I haven't checked again.
