### ISSUE TITLE
Cannot read properties of undefined (reading 'security_enabled')

### ISSUE THREAD

**Issue by konstantin-p-petrov** [fescobar/allure-docker-service-ui#25]
Hello, I am trying to start the Allure UI in docker without success.
My setup is a virtual machine in Azure and has nginx container which exposes the public IP of the machine.
I have exposed the 5252 port of allure-docker-service-ui and when  I try to login receiving: Cannot read properties of undefined (reading 'security_enabled')
Code snipped of docker-compose file:
version: '3'
services:
  allure:
    image: "frankescobar/allure-docker-service"
    environment:
      CHECK_RESULTS_EVERY_SECONDS: NONE
      KEEP_HISTORY: 1
      KEEP_HISTORY_LATEST: 25
      SECURITY_USER: admin
      SECURITY_PASS: admin
      SECURITY_VIEWER_USER: "view_user"
      SECURITY_VIEWER_PASS: "view_pass"
      SECURITY_ENABLED: 1
      MAKE_VIEWER_ENDPOINTS_PUBLIC: 1
    ports:
      - "5050:5050"
    volumes:
      - /home/azureuser/projects:/app/projects

  allure-ui:
    image: "frankescobar/allure-docker-service-ui:7.0.0"
    environment:
      ALLURE_DOCKER_PUBLIC_API_URL: "http://vm-ip-address/"
      ALLURE_DOCKER_PUBLIC_API_URL_PREFIX: "/api"
    ports:
      - "5252:5252"

**Comment by fescobar** [comment]
Try to check if UI has access to API. Try with the security disabled too.
it's a network configuration.
