### ISSUE TITLE
Accessing allure-docker-service-ui using ip address in  different host create "Network error"

### ISSUE THREAD

**Issue by saurabh4888** [fescobar/allure-docker-service-ui#28]
Starting docker UI container in different host and then try to access the UI with IP address in other host pc ,

throws below issue. Please let know which configuration needed to make UI also access into different host 

"_Network Error"
Check if you have access to http://localhost:5050/allure-docker-service
Or pull the latest "frankescobar/allure-docker-service" API image (remove your current latest version)
{"message":"Network Error","name":"Error","stack":"Error: Network Error\n at e.exports (http://192.168.165.129:5252/static/js/2.fc83d11e.chunk.js:2:70398)\n at p.onerror (http://192.168.165.129:5252/static/js/2.fc83d11e.chunk.js:2:69367)","config":{"url":"/config","method":"get","headers":{"Accept":"application/json, text/plain, */*"},"baseURL":"http://localhost:5050/allure-docker-service","transformRequest":[null],"transformResponse":[null],"timeout":0,"xsrfCookieName":"XSRF-TOKEN","xsrfHeaderName":"X-XSRF-TOKEN","maxContentLength":-1,"maxBodyLength":-1,"withCredentials":true_

**Comment by fescobar** [comment]
API and UI containers must share the same domain. You need to deploy the containers using Kubernetes with a proper domain configured.
