### ISSUE TITLE
Project is dead?

### ISSUE THREAD

**Issue by duchu** [fescobar/allure-docker-service-ui#29]
Allure allready have few updates which are not present in this repo. My question is are planning any upadtes in near future?

**Comment by fescobar** [comment]
`Allure Framework` the native framework is a complex project technically speaking. There are a lot of things they need to fix to continue making some improvements in Allure Docker Service API and UI. Currently, we have some limitations to improving this.

**Comment by manuschillerdev** [comment]
@fescobar Are there some concrete points the community could help with?
I love this project, and I'd love to help to make it compatible with recent allure2 versions! :)
