### ISSUE TITLE
Invalid Token - Signature verification failed while UI login 

### ISSUE THREAD

**Issue by Kamalb2592** [fescobar/allure-docker-service-ui#30]
@fescobar I am getting 401 error while login to UI.
{"meta_data":{"message":"Invalid Token - Signature verification failed"}}

Also the Network log from browser says 401 unauthorized for reuested URL https://<service-url>/allure-api/allure-docker-service/config 
Request Method: GET Status Code: 401 Remote Address: 127.0.0.1:9000 Referrer Policy: strict-origin-when-cross-origin

**Comment by fescobar** [comment]
@Kamalb2592 can you add more info like versions, steps, etc?

**Comment by Kamalb2592** [comment]
We have deployed this allure service on eks cluster and the service is accessible post that.
For deploying this application we have used this repo of yours https://github.com/fescobar/allure-docker-service-examples/tree/master/allure-docker-kubernetes-example 
The version i am using is the latest one. Below is the errors i am getting 

<img width="1784" alt="Screenshot 2022-08-29 at 8 32 41 PM" src="https://user-images.githubusercontent.com/33866295/187232446-3dd82a14-4b2f-48ae-a162-1fbc1fc60bb3.png">
<img width="841" alt="Screenshot 2022-08-29 at 8 32 48 PM" src="https://user-images.githubusercontent.com/33866295/187232456-43f0741d-b0c1-43ee-a766-17a3dc750f75.png">

**Comment by fescobar** [comment]
@Kamalb2592 api and ui are deployed in the same domain?

**Comment by fescobar** [comment]
@Kamalb2592 if you are using different instances you have to release your own version.
https://github.com/fescobar/allure-docker-service/pull/193
I will release that fix in a few hours.

**Comment by fescobar** [comment]
@Kamalb2592 The version `2.19.0` was released https://github.com/fescobar/allure-docker-service/releases/tag/v2.19.0
There was a pull request adding the multi-instance signing.
Just you need to add the env var `JWT_SECRET_KEY ` with your value.
https://github.com/fescobar/allure-docker-service#multi-instance-setup

**Comment by Kamalb2592** [comment]
Thanks, @fescobar I am able to log in now but sometime i am getting 404 error while accessing the project or while creatig new project from UI.
<img width="1590" alt="Screenshot 2022-08-30 at 12 50 53 PM" src="https://user-images.githubusercontent.com/33866295/187375409-4781ac98-2171-445c-b765-9e494e19e6d9.png">

**Comment by fescobar** [comment]
@Kamalb2592 the projects are directories created in the instance, we are not saving that in a database where is everything centralized. That is the reason I was not supporting multiple instances from the beginning. This project is only for 1 instance. 
If you use a shared mounted volume between instances maybe you won't have that issue.
