### ISSUE TITLE
Increase Allure UI Session Timeout

### ISSUE THREAD

**Issue by ssantrosyan** [fescobar/allure-docker-service-ui#32]
I am running images for allure-ui and allure-api from dockerhub in a hashicorp nomad and have a problem with Session Timeout. So after 15 minutes of getting logout from Allure-UI. How I can increase the session timeout to 1h and to not log in to a UI every 15 minutes?
Thanks

**Comment by fescobar** [comment]
https://github.com/fescobar/allure-docker-service#refresh-access-token
