### ISSUE TITLE
Network error when accessing Allure Docker UI

### ISSUE THREAD

**Issue by MarkWiesenthal** [fescobar/allure-docker-service-ui#39]
Hey, this was also mentioned in some other issues, but I have the same problem when accessing the UI:

"Network Error"
Check if you have access to http://localhost:5050/allure-docker-service
Or pull the latest "frankescobar/allure-docker-service" API image (remove your current latest version)
{"message":"Network Error","name":"Error","stack":"Error: Network Error\n at e.exports (https://allure-test-server-alb-1742797405.eu-central-1.elb.amazonaws.com/static/js/2.fc83d11e.chunk.js:2:70398)\n at p.onerror (https://allure-test-server-alb-1742797405.eu-central-1.elb.amazonaws.com/static/js/2.fc83d11e.chunk.js:2:69367)","config":{"url":"/config","method":"get","headers":{"Accept":"application/json, text/plain, */*"},"baseURL":"http://localhost:5050/allure-docker-service","transformRequest":[null],"transformResponse":[null],"timeout":0,"xsrfCookieName":"XSRF-TOKEN","xsrfHeaderName":"X-XSRF-TOKEN","maxContentLength":-1,"maxBodyLength":-1,"withCredentials":true}}

I am running both containers on one EC2 instance, all needed ports are open. 
I use a AWS load balancer for authentication; all ports are open there too.

**Comment by fescobar** [comment]
You need to deploy both containers using the same domain
