### ISSUE TITLE
Report added scenarios and errors 

### ISSUE THREAD

**Issue by uralrabo** [fescobar/allure-docker-service-ui#40]
Hello,

Unfortunately, the number of scenarios and the errors of the previous reports are transferred to the newly created report. What do I have to configure to turn this off?

thanks

**Comment by fescobar** [comment]
@uralrabo Please read the note here https://github.com/fescobar/allure-docker-service?tab=readme-ov-file#MULTIPLE-PROJECTS---REMOTE-REPORTS
