### ISSUE TITLE
Is there a way to see more than 20 reports in dropdown on UI?

### ISSUE THREAD

**Issue by SohanTirpude** [fescobar/allure-docker-service-ui#41]
Hello all,

Is there a way to see more than 20 reports in dropdown on UI? 

<img width="1716" alt="Screenshot 2024-02-19 at 2 01 12 AM" src="https://github.com/fescobar/allure-docker-service-ui/assets/13250447/9267fbb4-9c05-46c7-9d7e-8bd75ca6a264">

I have added `KEEP_HISTORY_LATEST` to 40 to `allure-docker-service` docker file but still I am seeing only 20 reports only.

**Comment by fescobar** [comment]
```sh
    environment:
      KEEP_HISTORY_LATEST: 28
```
Set that env var in Allure Docker Service API      
https://github.com/fescobar/allure-docker-service?tab=readme-ov-file#keep-history-and-trends
