### ISSUE TITLE
Handle admin/viewer roles

### ISSUE THREAD

**Issue by AnpooSivanadi-okta** [fescobar/allure-docker-service-ui#6]
Currently we have the UI with all the following functionalities.

<img width="1253" alt="Screen Shot 2020-09-10 at 10 50 12 AM" src="https://user-images.githubusercontent.com/57272894/92775645-6fb21b80-f353-11ea-831a-8a8a4337dc12.png">

which are more relevant to admins.

In case of opening up this report to wider audience who do not need these features, can we have a sepearate page with just

- Get Emailable Report
- Export Emailable Report
- Export Full Report

**Comment by fescobar** [comment]
@AnpooSivanadi-okta let me add it to the backlog.

**Comment by fescobar** [comment]
@AnpooSivanadi-okta 

To see reflected the new feature `Admin/Viewer roles`  use any version of API container from `2.13.7` and use any version of UI container from `7.0.1`

**allure-docker-service (API)**
https://github.com/fescobar/allure-docker-service/releases/tag/v2.13.7

**allure-docker-service (UI)**
https://github.com/fescobar/allure-docker-service-ui/releases/tag/v7.0.1

Thank you for your suggestions.
