### ISSUE TITLE
NETWORK ERROR

### ISSUE THREAD

**Issue by digibank-rons** [fescobar/allure-docker-service-ui#8]
Hey,

trying to run the solution on K8s getting - 
""Network Error"
Check if you have access to http://allure-service.allure-oss:5050/allure-docker-service
Or pull the latest "frankescobar/allure-docker-service" API image (remove your current latest version)
{"message":"Network Error","name":"Error","stack":"Error: Network Error\n at e.exports (http://localhost:5252/static/js/2.305ecc37.chunk.js:2:69537)\n at XMLHttpRequest.p.onerror (http://localhost:5252/static/js/2.305ecc37.chunk.js:2:68488)","config":{"url":"/config","method":"get","headers":{"Accept":"application/json, text/plain, */*"},"baseURL":"http://allure-service.allure-oss:5050/allure-docker-service","transformRequest":[null],"transformResponse":[null],"timeout":0,"xsrfCookieName":"XSRF-TOKEN","xsrfHeaderName":"X-XSRF-TOKEN","maxContentLength":-1,"withCredentials":true}}"

No matter what I try.

Thanks,

Ron

**Comment by fescobar** [comment]
@digibank-rons can you access to http://allure-service.allure-oss:5050/allure-docker-service from your browser?
Did you have the latest allure-docker-service image (remove your previous latest)?
