### ISSUE TITLE
@zhaoyi007 To be sure that you are using the latest version, use the tag `2.13.6`

### ISSUE THREAD

**Issue by zhaoyi007** [fescobar/allure-docker-service-ui#9]
@zhaoyi007 To be sure that you are using the latest version, use the tag `2.13.6`

```sh
    image: "frankescobar/allure-docker-service:2.13.6"
    environment:
      CHECK_RESULTS_EVERY_SECONDS: 1
      KEEP_HISTORY: 1
    ports:
      - "5050:5050"
    volumes:
      - ${PWD}/allure-results:/app/allure-results
      - ${PWD}/allure-reports:/app/default-reports
```
In case it doesn't work share your docker-compose?

_Originally posted by @fescobar in https://github.com/fescobar/allure-docker-service-ui/issues/4#issuecomment-742419621_

**Comment by zhaoyi007** [comment]
First of all, thank you for your answer
I used the pytest example
-------------
version: '3'

services:
  allure:
    image: "frankescobar/allure-docker-service"
    environment:
      CHECK_RESULTS_EVERY_SECONDS: 1
      KEEP_HISTORY: 1
    ports:
      - "5050:5050"
    volumes:
      - ${PWD}/allure-results:/app/allure-results
      - ${PWD}/allure-reports:/app/default-reports

  allure-ui:
    image: "frankescobar/allure-docker-service-ui"
    environment:
      ALLURE_DOCKER_PUBLIC_API_URL: "http://localhost:5050"
      ALLURE_DOCKER_PUBLIC_API_URL_PREFIX: ""
    ports:
      - "5252:5252"



------------------------------------------------
This is the container log

allure-ui_1  | ALLURE_DOCKER_API_URL=http://localhost:5050/allure-docker-service
allure-ui_1  | ROUTER_BASE_NAME=/allure-docker-service-ui
allure_1     | Overriding configuration
allure_1     | Checking Allure Results every 1 second/s
allure_1     | ALLURE_VERSION: 2.13.6
allure_1     | Generating default report
allure_1     | Creating executor.json for PROJECT_ID: default
allure_1     | /app/generateAllureReport.sh: line 59: /app/allure-docker-api/static/projects/default/results/executor.json: Permission denied
allure_1     | Generating report for PROJECT_ID: default
allure_1     | [INFO] /app/allure-docker-api/app.py:163 Setting SECURITY_ENABLED=0 by default
allure_1     | Could not generate report
allure_1     | java.nio.file.AccessDeniedException: /app/allure-docker-api/static/projects/default/reports/latest
allure_1     | 	at java.base/sun.nio.fs.UnixException.translateToIOException(Unknown Source)
allure_1     | 	at java.base/sun.nio.fs.UnixException.rethrowAsIOException(Unknown Source)
allure_1     | 	at java.base/sun.nio.fs.UnixException.rethrowAsIOException(Unknown Source)
allure_1     | 	at java.base/sun.nio.fs.UnixFileSystemProvider.createDirectory(Unknown Source)
allure_1     | 	at java.base/java.nio.file.Files.createDirectory(Unknown Source)
allure_1     | 	at java.base/java.nio.file.Files.createAndCheckIsDirectory(Unknown Source)
allure_1     | 	at java.base/java.nio.file.Files.createDirectories(Unknown Source)
allure_1     | 	at io.qameta.allure.CommonJsonAggregator.aggregate(CommonJsonAggregator.java:51)
allure_1     | 	at io.qameta.allure.CompositeAggregator.aggregate(CompositeAggregator.java:43)
allure_1     | 	at io.qameta.allure.ReportGenerator.aggregate(ReportGenerator.java:53)
allure_1     | 	at io.qameta.allure.ReportGenerator.generate(ReportGenerator.java:70)
allure_1     | 	at io.qameta.allure.ReportGenerator.generate(ReportGenerator.java:58)
allure_1     | 	at io.qameta.allure.Commands.generate(Commands.java:104)
allure_1     | 	at io.qameta.allure.CommandLine.run(CommandLine.java:152)
allure_1     | 	at io.qameta.allure.CommandLine$$Lambda$11/00000000F0339F40.get(Unknown Source)
allure_1     | 	at java.base/java.util.Optional.orElseGet(Unknown Source)
allure_1     | 	at io.qameta.allure.CommandLine.main(CommandLine.java:88)
allure_1     | ls: cannot access '/app/allure-docker-api/static/projects/default/reports/*': No such file or directory
allure_1     | Retrying call http://localhost:5050/allure-docker-service/emailable-report/render?project_id=default in 2 seconds
allure_1     | Retrying call http://localhost:5050/allure-docker-service/emailable-report/render?project_id=default in 2 seconds

**Comment by fescobar** [comment]
@zhaoyi007 that is a different problem not related to the UI. It's related to the backend, it's different github repo.
You have a problem with permissions.
https://github.com/fescobar/allure-docker-service/issues/108

**Comment by zhaoyi007** [comment]
Thank you. The problem has been solved. just configure user to switch to root in docker-compose.yaml

Your image is very good. It helps me a lot!
